# Generated by Django 6.0.4 on 2026-05-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('surname', models.CharField(max_length=128, null=True)),
                ('add_day', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('class_type', models.IntegerField(null=True)),
            ],
        ),
    ]
